version: '3'
services:
  db:
    image: postgres
    container_name: postgres-for-app
    volumes:
      - postgres:/var/run/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "5432:5432"
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app-storage:/rails/storage
    ports:
      - "3002:3000"
    depends_on:
      - db
volumes:
  postgres:
  app-storage:
  bundler_gems:

networks:
  default: