default: &default
  adapter: postgresql
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: db
  username: <%= ENV['POSTGRES_USER']%>
  password: <%= ENV['POSTGRES_PASSWORD']%>

test:
  <<: *default
  database: db_test
  username: <%= ENV['POSTGRES_USER']%>
  password: <%= ENV['POSTGRES_PASSWORD']%>

production:
  <<: *default
  database: db_prod
  username: <%= ENV['POSTGRES_USER']%>
  password: <%= ENV['POSTGRES_PASSWORD']%>
